# Generated by Django 5.0.3 on 2024-04-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='url',
            field=models.ImageField(default='test.jpg', upload_to=None),
        ),
    ]
